name: Build Weather Clear app and release with GitHub Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
      - run: flutter pub get
      - run: echo "API_KEY=${{ secrets.API_KEY }} \n WAQI_TOKEN=${{ secrets.WAQI_TOKEN }}" >> .env
      - run: flutter build apk
      - run: flutter build ios --release --no-codesign

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload Release Assets
        uses: actions/upload-artifact@v2
        with:
          name: release-assets
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/ios/iphoneos/Runner.app

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release App
          draft: false
          prerelease: false

      - name: Upload Release Assets
        id: upload-release-assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: WeatherClear-Android.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Release Assets
        id: upload-release-assets-ios
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/ios/iphoneos/Runner.app
          asset_name: WeatherClear-iOS.zip
          asset_content_type: application/zip